// Math.min
console.log(Math.min());  // Infinity (нет аргументов)
console.log(Math.min(1, 2, 3, 5));  // 1 (обычные числа)
console.log(Math.min(-1, -2, -3));  // -3 (отрицательные числа)
console.log(Math.min(1, "5", 3));  // 1 (строка "5" преобразуется в число)
console.log(Math.min(1, "a", 3));  // NaN (строка "a" не может быть преобразована в число)
console.log(Math.min(1, null, 3));  // 0 (null преобразуется в 0)
console.log(Math.min(1, undefined, 3));  // NaN (undefined становится NaN)
console.log(Math.min(1, NaN, 3));  // NaN (NaN делает результат NaN)
console.log(Math.min(1, 2, Infinity));  // 1 (Infinity больше любого числа)
console.log(Math.min(1, -Infinity, 3));  // -Infinity (отрицательная бесконечность)
console.log(Math.min(0, -0));  // 0 (оба равны, результат 0)
console.log(Math.min(100, -100));  // -100 (сравнение больших чисел)
console.log(Math.min(100, 200, "50"));  // 50 (строка "50" преобразуется в число)
console.log(Math.min(5, 10, "100"));  // 5 (строка "100" преобразуется в число)
console.log(Math.min("10", 20));  // 10 (строка "10" преобразуется в число)
console.log(Math.min(true, false));  // false (true = 1, false = 0)
console.log(Math.min(1, 0, -1));  // -1 (сравнение положительных и отрицательных чисел)
console.log(Math.min("1", "2", "3"));  // 1 (строки будут преобразованы в числа)
console.log(Math.min(0, 0));  // 0 (пара одинаковых чисел)
console.log(Math.min("  5", " 3"));  // 3 (пробелы игнорируются, строки преобразуются в числа)



// Math.max
console.log(Math.max());  // -Infinity (нет аргументов)
console.log(Math.max(1, 2, 3, 5));  // 5 (обычные числа)
console.log(Math.max(-1, -2, -3));  // -1 (отрицательные числа)
console.log(Math.max(1, "5", 3));  // 5 (строка "5" преобразуется в число)
console.log(Math.max(1, "a", 3));  // NaN (строка "a" не может быть преобразована в число)
console.log(Math.max(1, null, 3));  // 3 (null преобразуется в 0)
console.log(Math.max(1, undefined, 3));  // NaN (undefined становится NaN)
console.log(Math.max(1, NaN, 3));  // NaN (NaN делает результат NaN)
console.log(Math.max(1, 2, Infinity));  // Infinity (Infinity больше любого числа)
console.log(Math.max(1, -Infinity, 3));  // 3 (отрицательная бесконечность меньше любого числа)
console.log(Math.max(0, -0));  // 0 (оба равны, результат 0)
console.log(Math.max(100, -100));  // 100 (сравнение больших чисел)
console.log(Math.max(100, 200, "50"));  // 200 (строка "50" преобразуется в число)
console.log(Math.max(5, 10, "100"));  // 100 (строка "100" преобразуется в число)
console.log(Math.max("10", 20));  // 20 (строка "10" преобразуется в число)
console.log(Math.max(true, false));  // true (true = 1, false = 0)
console.log(Math.max(1, 0, -1));  // 1 (сравнение положительных и отрицательных чисел)
console.log(Math.max("1", "2", "3"));  // 3 (строки будут преобразованы в числа)
console.log(Math.max(0, 0));  // 0 (пара одинаковых чисел)
console.log(Math.max("  5", " 3"));  // 5 (пробелы игнорируются, строки преобразуются в числа)



// Math.floor
console.log(Math.floor(1.5));  // 1 (округление в меньшую сторону)
console.log(Math.floor(0.1));  // 0 (округление в меньшую сторону)
console.log(Math.floor(-0.5));  // -1 (округление в меньшую сторону для отрицательных чисел)
console.log(Math.floor(10));  // 10 (целое число не меняется)
console.log(Math.floor("10.7"));  // 10 (строка преобразуется в число)
console.log(Math.floor("a"));  // NaN (непреобразуемая строка)
console.log(Math.floor(null));  // 0 (null преобразуется в 0)
console.log(Math.floor(undefined));  // NaN (undefined не может быть преобразовано)
console.log(Math.floor(NaN));  // NaN (NaN остается NaN)
console.log(Math.floor(Infinity));  // Infinity (положительная бесконечность)
console.log(Math.floor(-Infinity));  // -Infinity (отрицательная бесконечность)
console.log(Math.floor(0));  // 0 (нулевое число)
console.log(Math.floor("123.45"));  // 123 (строка преобразуется в число)
console.log(Math.floor(10.1));  // 10 (округление в меньшую сторону)
console.log(Math.floor(0.99));  // 0 (округление в меньшую сторону)
console.log(Math.floor(true));  // 1 (true преобразуется в 1)
console.log(Math.floor(false));  // 0 (false преобразуется в 0)
console.log(Math.floor("10.9"));  // 10 (округление до целого числа)
console.log(Math.floor([1.1, 2.2]));  // NaN (массив не может быть преобразован в число)
console.log(Math.floor({}));  // NaN (объект не может быть преобразован в число)



// Math.ceil
console.log(Math.ceil(1.5));  // 2 (округление в большую сторону)
console.log(Math.ceil(0.1));  // 1 (округление в большую сторону)
console.log(Math.ceil(-0.5));  // 0 (округление в большую сторону для отрицательных чисел)
console.log(Math.ceil(10));  // 10 (целое число не меняется)
console.log(Math.ceil("10.7"));  // 11 (строка преобразуется в число)
console.log(Math.ceil("a"));  // NaN (непреобразуемая строка)
console.log(Math.ceil(null));  // 0 (null преобразуется в 0)
console.log(Math.ceil(undefined));  // NaN (undefined не может быть преобразовано)
console.log(Math.ceil(NaN));  // NaN (NaN остается NaN)
console.log(Math.ceil(Infinity));  // Infinity (положительная бесконечность)
console.log(Math.ceil(-Infinity));  // -Infinity (отрицательная бесконечность)
console.log(Math.ceil(0));  // 0 (нулевое число)
console.log(Math.ceil("123.45"));  // 124 (строка преобразуется в число)
console.log(Math.ceil(10.1));  // 11 (округление в большую сторону)
console.log(Math.ceil(0.99));  // 1 (округление в большую сторону)
console.log(Math.ceil(true));  // 1 (true преобразуется в 1)
console.log(Math.ceil(false));  // 0 (false преобразуется в 0)
console.log(Math.ceil("10.9"));  // 11 (округление в большую сторону)
console.log(Math.ceil([1.1, 2.2]));  // NaN (массив не может быть преобразован в число)
console.log(Math.ceil({}));  // NaN (объект не может быть преобразован в число)



// Math.round
console.log(Math.round(1.5));  // 2 (округление до ближайшего целого)
console.log(Math.round(0.1));  // 0 (округление до ближайшего целого)
console.log(Math.round(-0.5));  // -0 (округление до ближайшего целого для отрицательных чисел)
console.log(Math.round(10));  // 10 (целое число не меняется)
console.log(Math.round("10.7"));  // 11 (строка преобразуется в число)
console.log(Math.round("a"));  // NaN (непреобразуемая строка)
console.log(Math.round(null));  // 0 (null преобразуется в 0)
console.log(Math.round(undefined));  // NaN (undefined не может быть преобразовано)
console.log(Math.round(NaN));  // NaN (NaN остается NaN)
console.log(Math.round(Infinity));  // Infinity (положительная бесконечность)
console.log(Math.round(-Infinity));  // -Infinity (отрицательная бесконечность)
console.log(Math.round(0));  // 0 (нулевое число)
console.log(Math.round("123.45"));  // 123 (строка преобразуется в число)
console.log(Math.round(10.1));  // 10 (округление до ближайшего целого)
console.log(Math.round(0.99));  // 1 (округление до ближайшего целого)
console.log(Math.round(true));  // 1 (true преобразуется в 1)
console.log(Math.round(false));  // 0 (false преобразуется в 0)
console.log(Math.round("10.9"));  // 11 (округление до ближайшего целого)
console.log(Math.round([1.1, 2.2]));  // NaN (массив не может быть преобразован в число)
console.log(Math.round({}));  // NaN (объект не может быть преобразован в число)



// Math.trunc
console.log(Math.trunc(1.5));  // 1 (удаление дробной части)
console.log(Math.trunc(0.1));  // 0 (удаление дробной части)
console.log(Math.trunc(-0.5));  // -0 (удаление дробной части для отрицательных чисел)
console.log(Math.trunc(10));  // 10 (целое число не меняется)
console.log(Math.trunc("10.7"));  // 10 (строка преобразуется в число)
console.log(Math.trunc("a"));  // NaN (непреобразуемая строка)
console.log(Math.trunc(null));  // 0 (null преобразуется в 0)
console.log(Math.trunc(undefined));  // NaN (undefined не может быть преобразовано)
console.log(Math.trunc(NaN));  // NaN (NaN остается NaN)
console.log(Math.trunc(Infinity));  // Infinity (положительная бесконечность)
console.log(Math.trunc(-Infinity));  // -Infinity (отрицательная бесконечность)
console.log(Math.trunc(0));  // 0 (нулевое число)
console.log(Math.trunc("123.45"));  // 123 (строка преобразуется в число)
console.log(Math.trunc(10.1));  // 10 (удаление дробной части)
console.log(Math.trunc(0.99));  // 0 (удаление дробной части)
console.log(Math.trunc(true));  // 1 (true преобразуется в 1)
console.log(Math.trunc(false));  // 0 (false преобразуется в 0)
console.log(Math.trunc("10.9"));  // 10 (удаление дробной части)
console.log(Math.trunc([1.1, 2.2]));  // NaN (массив не может быть преобразован в число)
console.log(Math.trunc({}));  // NaN (объект не может быть преобразован в число)



// Math.abs
console.log(Math.abs(-5));  // 5 (отрицательное число становится положительным)
console.log(Math.abs(5));   // 5 (положительное число остаётся неизменным)
console.log(Math.abs(0));   // 0 (нулевое число остаётся 0)
console.log(Math.abs(-0));  // 0 (нулевое число остаётся 0)
console.log(Math.abs("10"));  // 10 (строка преобразуется в число)
console.log(Math.abs("-10"));  // 10 (строка с минусом преобразуется в число)
console.log(Math.abs("a"));  // NaN (строка не может быть преобразована в число)
console.log(Math.abs(null));  // 0 (null преобразуется в 0)
console.log(Math.abs(undefined));  // NaN (undefined не может быть преобразовано)
console.log(Math.abs(NaN));  // NaN (NaN остается NaN)
console.log(Math.abs(Infinity));  // Infinity (положительная бесконечность)
console.log(Math.abs(-Infinity));  // Infinity (отрицательная бесконечность становится положительной)
console.log(Math.abs(true));  // 1 (true преобразуется в 1)
console.log(Math.abs(false));  // 0 (false преобразуется в 0)
console.log(Math.abs([1]));  // 1 (массив преобразуется в 1)
console.log(Math.abs([1, 2]));  // NaN (массив с несколькими элементами не может быть преобразован в число)
console.log(Math.abs({}));  // NaN (объект не может быть преобразован в число)
console.log(Math.abs("123.45"));  // 123.45 (строка с числом преобразуется в число)
console.log(Math.abs(-123.45));  // 123.45 (отрицательное число становится положительным)
console.log(Math.abs("0"));  // 0 (строка "0" преобразуется в число)



// Math.random
console.log(Math.random());  // 0 <= x < 1 (генерирует случайное число от 0 до 1, но не включая 1)
console.log(Math.random() < 1);  // true (генерирует значение меньше 1, всегда true)
console.log(Math.random() === Math.random());  // false (каждое значение случайное)
console.log(Math.random() * 100);  // от 0 до 100 (случайное число от 0 до 100)
console.log(Math.random() * 1000);  // от 0 до 1000 (случайное число от 0 до 1000)
console.log(Math.random() * 0);  // 0 (умножение на 0 даёт 0)
console.log(Math.random() + 5);  // от 5 до 6 (случайное число от 5 до 6)
console.log(Math.random() - 1);  // от -1 до 0 (случайное число от -1 до 0)
console.log(Math.floor(Math.random() * 10));  // целое число от 0 до 9 (округление вниз до ближайшего целого)
console.log(Math.floor(Math.random() * 100));  // целое число от 0 до 99
console.log(Math.floor(Math.random() * 1000));  // целое число от 0 до 999
console.log(Math.floor(Math.random() * 10) === Math.floor(Math.random() * 10));  // true или false (сравнение случайных чисел)
console.log(Math.random() === 0);  // false (случайное число всегда больше 0)
console.log(Math.random() === 1);  // false (случайное число всегда меньше 1)
console.log(Math.random() * -10);  // от -10 до 0 (случайное число от -10 до 0)
console.log(Math.random() + "test");  // случайное число, преобразованное в строку
console.log(Math.random() > 0.5);  // true или false (случайное число больше или меньше 0.5)
console.log(Math.random() * 100 + 1000);  // от 1000 до 1100 (случайное число от 1000 до 1100)
console.log(Math.random() * 1000 - 1000);  // от -1000 до 0 (случайное число от -1000 до 0)


